export const companies = [
  { id: 1, name: "Yamaha Motor Co." },
  { id: 2, name: "Honda Motor Co." },
  { id: 3, name: "Suzuki Motor Corporation" },
  { id: 4, name: "Kawasaki Heavy Industries" },
  { id: 5, name: "Ducati Motor Holding" },
  { id: 6, name: "BMW Motorrad" },
  { id: 7, name: "Harley-Davidson, Inc." },
  { id: 8, name: "KTM AG" },
  { id: 9, name: "Triumph Motorcycles Ltd." },
  { id: 10, name: "Indian Motorcycle Company" },
  { id: 11, name: "Vento Bikes" },
  { id: 12, name: "Bajaj Auto" },
  { id: 13, name: "Royal Enfield" },
  { id: 14, name: "Aprilia" },
  { id: 15, name: "Moto Guzzi" },
  { id: 16, name: "CFMoto" },
  { id: 17, name: "Benelli" },
  { id: 18, name: "SYM Motors" },
  { id: 19, name: "Hero MotoCorp" },
  { id: 20, name: "Lifan Motorcycles" },
  { id: 21, name: "Rieju" },
  { id: 22, name: "GasGas" },
  { id: 23, name: "Sherco" },
  { id: 24, name: "Vento Racing" },
];
